apiVersion: v1
kind: Namespace
metadata:
  name: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: zk-s
  namespace: kafka
  labels:
    app: zk-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zk-1

---

apiVersion: v1
kind: Deployment
metadata:
  name: zk-deployment-1
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        app: zk-1
    spec:
      containers:
      - name: zk1
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zk1

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafkaApp
  name: kafka
  namespace: kafka
spec:
   ports:
     - port: 9092
       targetPort: 9092
       protocol: TCP
     - port: 2181
       targetPort: 2181
   selector:
     app: kafkaApp
   type: LoadBalancer

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafkaApp
  name: kafka-repcon
  namespace: kafka
spec:
   replicas: 1
   selector:
     app: kafkaApp
   template:
     metadata:
       labels:
         app: kafkaApp
     spec:
       containers:
       - command:
          - zookeeper-server-start.sh
          - /config/zookeeper.properties
         image: "wurstmeister/kafka" 
         name: zk1
         ports:
         - containerPort: 2181

